package com.amg.exchange.model;

// default package
// Generated May 23, 2014 5:18:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * BankMaster generated by hbm2java
 */
@Entity
@Table(name = "EX_BANK_MASTER")
public class BankMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal bankId;
	private StateMaster fsStateMaster;
	private CityMaster fsCityMaster;
	private CountryMaster fsCountryMaster;
	private DistrictMaster fsDistrictMaster;
	private String bankCode;
	private String bankFullName;
	private String bankShortName;
	private String address1;
	private String address2;
	private String zipCode;
	private String teleponeNo;
	private String faxNo;
	private String email;
	private String recordStatus;
	private String bankFullNameAr;
	private String bankShortNameAr;
	private String address1Ar;
	private String address2Ar;
	private String languageInd;
	private String fileBranch;
	private String fileRemitMode;
	private String fileAlls;
	private BigDecimal ifscLen;
	private String reutersBankName;
	private String creator;
	private Date createDate;
	private Date updateDate;
	private String modifier;
	private String micrCode;	/*
	 * private Set exBankContactDetailses = new HashSet(0); private Set
	 * exBankAccountLengths = new HashSet(0); private Set exBankBranches = new
	 * HashSet(0); private Set exBankAccounts = new HashSet(0); private Set
	 * exBankApplicabilities = new HashSet(0); private Set
	 * exBankAccountDetailses = new HashSet(0);
	 */
	private List<BankContactDetails> exBankContactDetailses = new ArrayList<BankContactDetails>();
	private List<BankAccountLength> exBankAccountLengths = new ArrayList<BankAccountLength>();
	private List<BankBranch> exBankBranches = new ArrayList<BankBranch>();
	private List<BankAccount> exBankAccounts = new ArrayList<BankAccount>();
	private List<BankApplicability> exBankApplicabilities = new ArrayList<BankApplicability>();
	private List<BankAccountDetails> exBankAccountDetailses = new ArrayList<BankAccountDetails>();

	public BankMaster() {
	}

	public BankMaster(BigDecimal bankId) {
		this.bankId = bankId;
	}

	public BankMaster(BigDecimal bankId, StateMaster fsStateMaster,
			CityMaster fsCityMaster, CountryMaster fsCountryMaster,
			String bankCode, String bankFullName, String bankShortName,
			String address1, String address2, String zipCode,
			String teleponeNo, String faxNo, String email, String recordStatus,
			String bankFullNameAr, String bankShortNameAr, String address1Ar,
			String address2Ar, String languageInd, String fileBranch,
			String fileRemitMode, String fileAlls, BigDecimal ifscLen,
			String reutersBankName, String creator, Date createDate,
			String micrCode,
			Date updateDate, String modifier, DistrictMaster fsDistrictMaster,
			List<BankContactDetails> exBankContactDetailses,
			List<BankAccountLength> exBankAccountLengths,
			List<BankBranch> exBankBranches, List<BankAccount> exBankAccounts,
			List<BankApplicability> exBankApplicabilities,
			List<BankAccountDetails> exBankAccountDetailses) {
		this.bankId = bankId;
		this.fsStateMaster = fsStateMaster;
		this.fsCityMaster = fsCityMaster;
		this.fsCountryMaster = fsCountryMaster;
		this.bankCode = bankCode;
		this.bankFullName = bankFullName;
		this.bankShortName = bankShortName;
		this.address1 = address1;
		this.address2 = address2;
		this.zipCode = zipCode;
		this.teleponeNo = teleponeNo;
		this.faxNo = faxNo;
		this.email = email;
		this.recordStatus = recordStatus;
		this.bankFullNameAr = bankFullNameAr;
		this.bankShortNameAr = bankShortNameAr;
		this.address1Ar = address1Ar;
		this.address2Ar = address2Ar;
		this.languageInd = languageInd;
		this.fileBranch = fileBranch;
		this.fileRemitMode = fileRemitMode;
		this.fileAlls = fileAlls;
		this.ifscLen = ifscLen;
		this.reutersBankName = reutersBankName;
		this.creator = creator;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.modifier = modifier;
		this.exBankContactDetailses = exBankContactDetailses;
		this.exBankAccountLengths = exBankAccountLengths;
		this.exBankBranches = exBankBranches;
		this.exBankAccounts = exBankAccounts;
		this.exBankApplicabilities = exBankApplicabilities;
		this.exBankAccountDetailses = exBankAccountDetailses;
		this.fsDistrictMaster = fsDistrictMaster;
		this.micrCode=micrCode;
	}

	@Id
	@TableGenerator(name = "bankid", table = "ex_bankidpk", pkColumnName = "bankidkey", pkColumnValue = "bankidvalue", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "bankid")
	@Column(name = "BANK_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getBankId() {
		return this.bankId;
	}

	public void setBankId(BigDecimal bankId) {
		this.bankId = bankId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public StateMaster getFsStateMaster() {
		return this.fsStateMaster;
	}

	public void setFsStateMaster(StateMaster fsStateMaster) {
		this.fsStateMaster = fsStateMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY_ID")
	public CityMaster getFsCityMaster() {
		return this.fsCityMaster;
	}

	public void setFsCityMaster(CityMaster fsCityMaster) {
		this.fsCityMaster = fsCityMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_ID")
	public CountryMaster getFsCountryMaster() {
		return this.fsCountryMaster;
	}

	public void setFsCountryMaster(CountryMaster fsCountryMaster) {
		this.fsCountryMaster = fsCountryMaster;
	}

	@Column(name = "BANK_CODE", length = 10)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "BANK_FULL_NAME", length = 150)
	public String getBankFullName() {
		return this.bankFullName;
	}

	public void setBankFullName(String bankFullName) {
		this.bankFullName = bankFullName;
	}

	@Column(name = "BANK_SHORT_NAME", length = 80)
	public String getBankShortName() {
		return this.bankShortName;
	}

	public void setBankShortName(String bankShortName) {
		this.bankShortName = bankShortName;
	}

	@Column(name = "ADDRESS1", length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ZIP_CODE", length = 15)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "TELEPONE_NO", length = 30)
	public String getTeleponeNo() {
		return this.teleponeNo;
	}

	public void setTeleponeNo(String teleponeNo) {
		this.teleponeNo = teleponeNo;
	}

	@Column(name = "FAX_NO", length = 30)
	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "BANK_FULL_NAME_AR", length = 150)
	public String getBankFullNameAr() {
		return this.bankFullNameAr;
	}

	public void setBankFullNameAr(String bankFullNameAr) {
		this.bankFullNameAr = bankFullNameAr;
	}

	@Column(name = "BANK_SHORT_NAME_AR", length = 100)
	public String getBankShortNameAr() {
		return this.bankShortNameAr;
	}

	public void setBankShortNameAr(String bankShortNameAr) {
		this.bankShortNameAr = bankShortNameAr;
	}

	@Column(name = "ADDRESS1_AR", length = 120)
	public String getAddress1Ar() {
		return this.address1Ar;
	}

	public void setAddress1Ar(String address1Ar) {
		this.address1Ar = address1Ar;
	}

	@Column(name = "ADDRESS2_AR", length = 120)
	public String getAddress2Ar() {
		return this.address2Ar;
	}

	public void setAddress2Ar(String address2Ar) {
		this.address2Ar = address2Ar;
	}

	@Column(name = "LANGUAGE_IND", length = 1)
	public String getLanguageInd() {
		return this.languageInd;
	}

	public void setLanguageInd(String languageInd) {
		this.languageInd = languageInd;
	}

	@Column(name = "FILE_BRANCH", length = 1)
	public String getFileBranch() {
		return this.fileBranch;
	}

	public void setFileBranch(String fileBranch) {
		this.fileBranch = fileBranch;
	}

	@Column(name = "FILE_REMIT_MODE", length = 1)
	public String getFileRemitMode() {
		return this.fileRemitMode;
	}

	public void setFileRemitMode(String fileRemitMode) {
		this.fileRemitMode = fileRemitMode;
	}

	@Column(name = "FILE_ALLS", length = 1)
	public String getFileAlls() {
		return this.fileAlls;
	}

	public void setFileAlls(String fileAlls) {
		this.fileAlls = fileAlls;
	}

	@Column(name = "IFSC_LEN", precision = 22, scale = 0)
	public BigDecimal getIfscLen() {
		return this.ifscLen;
	}

	public void setIfscLen(BigDecimal ifscLen) {
		this.ifscLen = ifscLen;
	}

	@Column(name = "REUTERS_BANK_NAME", length = 100)
	public String getReutersBankName() {
		return this.reutersBankName;
	}

	public void setReutersBankName(String reutersBankName) {
		this.reutersBankName = reutersBankName;
	}

	@Column(name = "CREATOR", length = 15)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATE_DATE")
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "MODIFIER", length = 15)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankContactDetails> getExBankContactDetailses() {
		return exBankContactDetailses;
	}

	public void setExBankContactDetailses(
			List<BankContactDetails> exBankContactDetailses) {
		this.exBankContactDetailses = exBankContactDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankAccountLength> getExBankAccountLengths() {
		return exBankAccountLengths;
	}

	public void setExBankAccountLengths(
			List<BankAccountLength> exBankAccountLengths) {
		this.exBankAccountLengths = exBankAccountLengths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankBranch> getExBankBranches() {
		return exBankBranches;
	}

	public void setExBankBranches(List<BankBranch> exBankBranches) {
		this.exBankBranches = exBankBranches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankAccount> getExBankAccounts() {
		return exBankAccounts;
	}

	public void setExBankAccounts(List<BankAccount> exBankAccounts) {
		this.exBankAccounts = exBankAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankApplicability> getExBankApplicabilities() {
		return exBankApplicabilities;
	}

	public void setExBankApplicabilities(
			List<BankApplicability> exBankApplicabilities) {
		this.exBankApplicabilities = exBankApplicabilities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exBankMaster")
	public List<BankAccountDetails> getExBankAccountDetailses() {
		return exBankAccountDetailses;
	}

	public void setExBankAccountDetailses(
			List<BankAccountDetails> exBankAccountDetailses) {
		this.exBankAccountDetailses = exBankAccountDetailses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRICT_ID", nullable = false)
	public DistrictMaster getFsDistrictMaster() {
		return fsDistrictMaster;
	}

	public void setFsDistrictMaster(DistrictMaster fsDistrictMaster) {
		this.fsDistrictMaster = fsDistrictMaster;
	}

	@Column(name = "MICR_CODE")
	public String getMicrCode() {
		return micrCode;
	}

	public void setMicrCode(String micrCode) {
		this.micrCode = micrCode;
	}

	
}
